### ISSUE TITLE
Virtual Machine Specification not available

### ISSUE THREAD

**Issue by ziqihuangg** [rohitgirdhar/CATER#10]
Dear Authors @rohitgirdhar ,

I tried to download and use the VM Spec but the downloaded spec_v0.img file is corrupted.

May I ask whether the link to download the VM spec is updated? 
Could you kindly share the working URL to download the VM spec for CATER?  

I used the download link in this webpage: https://cmu.box.com/s/krg7ehliaidruxjk21nfxsa0gge2uf2o, as provided in CATER-master/generate/README.md. However, when I tried to open the downloaded 3.0 GB spec_v0.img file, it says “The disc image file is corrupted”. If I specify the directory of the downloaded spec_v0.img file in launch.py and run launch.py, it prompts “singularity: not found”, as if there weren’t any spec_v0.img file. I have tried downloading and opening the spec_v0.img file on MacOS, Windows and Ubuntu, but all led to the same issue. I have tried using “wget” command to download the spec_v0.img file, but I didn’t find the specific URL for downloading. 

I'm interested in your work and would like to learn from it. 
Thank you very much!

**Comment by rohitgirdhar** [comment]
Hi @ziqihuangg thanks for your interest and apologies for the delay in responding.
The link should be correct, nevertheless I updated the link to a direct download link that should make it easier to download on a headless server. You can use something like 
```bash
$  wget https://cmu.box.com/shared/static/krg7ehliaidruxjk21nfxsa0gge2uf2o.im -O spec_0.img
$ singularity run spec_0.img
```
I just tried it using the img file downloaded from Box, and it seems to work for me on a different machine from where it was created. Perhaps there is some other issue in terms of your singularity installation? Maybe try running some standard singularity img file to see if this issue is specific to this img file?

**Comment by ziqihuangg** [comment]
Hi @rohitgirdhar, thank you for the direct download link. Now the `singularity run spec_0.img` command works well. 

However, when running launch.py, prompt was that 'no such file or directory' for blender. I have replaced blender_path in launch.py with the absolute directory to blender. I'm using blender 2.78c, and the same blender_path works for CLEVR. May I ask whether it might be due to the VM, or there might be some other causes? Thank you again!

**Comment by ziqihuangg** [comment]
Hi @rohitgirdhar thank you for the direct download link. Both singularity and the img work now :)
