### ISSUE TITLE
Broken zip files of pre-generated data.

### ISSUE THREAD

**Issue by sjtuytc** [rohitgirdhar/CATER#12]
Hi, I appreciate your wonderful work. However, when I unzip the pre-generated data downloaded from the direct links, it raises that some files inside are broken. I confirm that the size of the zip file is right and a simple retry doesn't get it right. How could I address it?

**Comment by sjtuytc** [comment]
I tried another server and the same error happens again!

**Comment by rohitgirdhar** [comment]
Thanks for your interest. It might be because the files were created on a mac OS, and I think there are potentially some difference in the zip implementation between mac and linux [[reference](https://apple.stackexchange.com/a/63409)]. Can you try to extract it on a mac? Or perhaps try the [`uncompress`](https://linux.die.net/man/1/uncompress) utility on linux?

**Comment by sjtuytc** [comment]
Sorry I cannot use Mac OS to unzip those files (because they're too large). I thought those files are provided for headless servers, so would you mind releasing a tar.gz or something I could unzip on Linux servers?

**Comment by rohitgirdhar** [comment]
The links have been updated and should uncompress fine with `unzip`. Please reopen if it still doesn't work.
